/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButtonPrimary: typeof import('./src/components/BaseButtonPrimary.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLayoutAuth: typeof import('./src/components/BaseLayoutAuth.vue')['default']
    BaseMusicButton: typeof import('./src/components/BaseMusicButton.vue')['default']
    BasePageTransition: typeof import('./src/components/BasePageTransition.vue')['default']
    CountryCodePopup: typeof import('./src/components/CountryCodePopup.vue')['default']
    Customer: typeof import('./src/components/Customer.vue')['default']
    Fireworks: typeof import('./src/components/Fireworks.vue')['default']
    FooterTabbar: typeof import('./src/components/FooterTabbar.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductCarousel: typeof import('./src/components/ProductCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsLang: typeof import('./src/components/SettingsLang.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    TopIcons: typeof import('./src/components/TopIcons.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
